[package]
name = "smb1_mesen2rta_autosplitter"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
asr = { git = "https://github.com/LiveSplit/asr", features = ["derive"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
codegen-units = 1
strip = true

[profile.release.build-override]
opt-level = 0
